#!/usr/bin/env python3
"""
Build config/book_pages.yaml — the id → book-page map used to deep-link a
*specific* book at quizly.pub/book/{id} (with the AI adviser CTA).

Source of truth: the pre-rendered book pages in the kvasir_proto site
(src/html/quizly.pub/book/<id>.html), each of which carries JSON-LD with the
book's title and author. We extract (id, title, author, lang) so the scanner
can resolve a thread's book mention to the exact catalog page.

Run:
    python scripts/build_book_pages.py
    python scripts/build_book_pages.py --pages-dir /path/to/quizly.pub/book
    python scripts/build_book_pages.py --dry-run
"""

from __future__ import annotations

import argparse
import glob
import os
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

DEFAULT_OUTPUT = REPO_ROOT / "config" / "book_pages.yaml"

_CYRILLIC = re.compile(r"[Ѐ-ӿ]")
_NAME_RE = re.compile(r'"@type":\s*"Book".*?"name":\s*"([^"]*)"', re.DOTALL)
_AUTHOR_RE = re.compile(r'"author":\s*\{[^}]*"name":\s*"([^"]*)"')
_TITLE_FALLBACK_RE = re.compile(r"<title>(.*?)\s+—\s+Book")


def _default_pages_dir() -> Path:
    """Derive the book-pages dir from the configured book-list path."""
    try:
        from src.settings import get_book_list_path

        # .../kvasir_proto/src/html/kvasir.pub/book-list.txt
        #  -> .../kvasir_proto/src/html/quizly.pub/book
        html_dir = get_book_list_path().resolve().parent.parent
        return html_dir / "quizly.pub" / "book"
    except Exception:
        return Path("quizly.pub/book")


def _lang(title: str) -> str:
    return "ru" if _CYRILLIC.search(title or "") else "en"


def extract_pages(pages_dir: Path) -> list[dict]:
    rows: list[dict] = []
    for path in glob.glob(str(pages_dir / "*.html")):
        bid = os.path.splitext(os.path.basename(path))[0]
        if not bid.isdigit():
            continue
        html = Path(path).read_text(encoding="utf-8", errors="ignore")
        m = _NAME_RE.search(html)
        title = m.group(1).strip() if m else ""
        if not title:
            m = _TITLE_FALLBACK_RE.search(html)
            title = m.group(1).strip() if m else ""
        if not title:
            continue
        a = _AUTHOR_RE.search(html)
        author = a.group(1).strip() if a else ""
        rows.append(
            {
                "id": int(bid),
                "title": title,
                "author": author,
                "lang": _lang(title),
            }
        )
    rows.sort(key=lambda r: r["id"])
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pages-dir", type=Path, default=_default_pages_dir())
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if not args.pages_dir.exists():
        sys.exit(f"ERROR: book pages dir not found: {args.pages_dir}")

    rows = extract_pages(args.pages_dir)
    ru = sum(1 for r in rows if r["lang"] == "ru")
    print(f"Extracted {len(rows)} book pages from {args.pages_dir} "
          f"({ru} ru, {len(rows) - ru} en)")

    if args.dry_run:
        for r in rows[:10]:
            print(" ", r)
        print("[dry-run] No file written.")
        return

    doc = {
        "url_template": "https://quizly.pub/book/{id}",
        "pages": rows,
    }
    args.output.write_text(
        "# AUTO-GENERATED by scripts/build_book_pages.py — do not edit by hand.\n"
        "# id -> specific book page (quizly.pub/book/{id}) for deep-link recommendations.\n"
        + yaml.dump(doc, allow_unicode=True, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )
    print(f"Written: {args.output}")


if __name__ == "__main__":
    main()
